require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MedicosController do

  # This should return the minimal set of attributes required to create a valid
  # Medico. As you add validations to Medico, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MedicosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all medicos as @medicos" do
      medico = Medico.create! valid_attributes
      get :index, {}, valid_session
      assigns(:medicos).should eq([medico])
    end
  end

  describe "GET show" do
    it "assigns the requested medico as @medico" do
      medico = Medico.create! valid_attributes
      get :show, {:id => medico.to_param}, valid_session
      assigns(:medico).should eq(medico)
    end
  end

  describe "GET new" do
    it "assigns a new medico as @medico" do
      get :new, {}, valid_session
      assigns(:medico).should be_a_new(Medico)
    end
  end

  describe "GET edit" do
    it "assigns the requested medico as @medico" do
      medico = Medico.create! valid_attributes
      get :edit, {:id => medico.to_param}, valid_session
      assigns(:medico).should eq(medico)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Medico" do
        expect {
          post :create, {:medico => valid_attributes}, valid_session
        }.to change(Medico, :count).by(1)
      end

      it "assigns a newly created medico as @medico" do
        post :create, {:medico => valid_attributes}, valid_session
        assigns(:medico).should be_a(Medico)
        assigns(:medico).should be_persisted
      end

      it "redirects to the created medico" do
        post :create, {:medico => valid_attributes}, valid_session
        response.should redirect_to(Medico.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved medico as @medico" do
        # Trigger the behavior that occurs when invalid params are submitted
        Medico.any_instance.stub(:save).and_return(false)
        post :create, {:medico => {}}, valid_session
        assigns(:medico).should be_a_new(Medico)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Medico.any_instance.stub(:save).and_return(false)
        post :create, {:medico => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested medico" do
        medico = Medico.create! valid_attributes
        # Assuming there are no other medicos in the database, this
        # specifies that the Medico created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Medico.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => medico.to_param, :medico => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested medico as @medico" do
        medico = Medico.create! valid_attributes
        put :update, {:id => medico.to_param, :medico => valid_attributes}, valid_session
        assigns(:medico).should eq(medico)
      end

      it "redirects to the medico" do
        medico = Medico.create! valid_attributes
        put :update, {:id => medico.to_param, :medico => valid_attributes}, valid_session
        response.should redirect_to(medico)
      end
    end

    describe "with invalid params" do
      it "assigns the medico as @medico" do
        medico = Medico.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Medico.any_instance.stub(:save).and_return(false)
        put :update, {:id => medico.to_param, :medico => {}}, valid_session
        assigns(:medico).should eq(medico)
      end

      it "re-renders the 'edit' template" do
        medico = Medico.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Medico.any_instance.stub(:save).and_return(false)
        put :update, {:id => medico.to_param, :medico => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested medico" do
      medico = Medico.create! valid_attributes
      expect {
        delete :destroy, {:id => medico.to_param}, valid_session
      }.to change(Medico, :count).by(-1)
    end

    it "redirects to the medicos list" do
      medico = Medico.create! valid_attributes
      delete :destroy, {:id => medico.to_param}, valid_session
      response.should redirect_to(medicos_url)
    end
  end

end
